# Import blocks generated by terraform-state-mover (TF 1.7+)
# Run: terraform apply (imports resource into this state)
# After successful apply, remove this file.

import {
  to = aws_iam_role.app_analytics_s3_access
  id = "arn:aws:iam::111111111111:role/app-analytics-s3-access"
}
