import type { DependencyGraph, CutEdge, MigrationStep, MigrationPlan, NamespaceConfig } from "../types.js";
import { findCrossNamespaceEdges } from "./cut-finder.js";

export function generateMigrationSteps(graph: DependencyGraph, cutEdges: CutEdge[]): MigrationStep[] {
  const steps: MigrationStep[] = [];

  for (const cut of cutEdges) {
    const fromNode = graph.nodes.get(cut.edge.from);
    const toNode = graph.nodes.get(cut.edge.to);
    if (!fromNode || !toNode) continue;

    // The resource to move: the "from" node should move to the "toNamespace"
    // because the edge crosses namespaces and the resource belongs in the target namespace
    steps.push({
      type: "state_mv",
      command: `terraform state mv -state=${fromNode.repo}/terraform.tfstate -state-out=${cut.toNamespace}/terraform.tfstate '${fromNode.resourceType}.${fromNode.name}' '${fromNode.resourceType}.${fromNode.name}'`,
      description: `Move ${fromNode.resourceType}.${fromNode.name} from ${fromNode.repo} to ${cut.toNamespace}`,
      resource: `${fromNode.resourceType}.${fromNode.name}`,
      targetRepo: cut.toNamespace,
    });

    // Import command for target
    steps.push({
      type: "import",
      command: `terraform import '${toNode.resourceType}.${toNode.name}' <RESOURCE_ID>`,
      description: `Import ${toNode.resourceType}.${toNode.name} into ${cut.toNamespace} state`,
      resource: `${toNode.resourceType}.${toNode.name}`,
      targetRepo: cut.toNamespace,
    });

    // Code rewrite step
    if (cut.edge.type === "arn") {
      steps.push({
        type: "code_rewrite",
        description: `Replace hardcoded ARN "${cut.edge.label}" with data source or variable reference`,
        resource: `${fromNode.resourceType}.${fromNode.name}`,
      });
    }
  }

  // Verification step
  steps.push({
    type: "verify",
    command: "terraform plan",
    description: "Verify no infrastructure changes after migration (expect no changes)",
  });

  return steps;
}

export function generateShellScript(steps: MigrationStep[]): string {
  const lines = [
    "#!/bin/bash",
    "set -euo pipefail",
    "",
    "# Terraform State Migration Script",
    "# Generated by terraform-state-mover",
    "",
  ];

  for (const step of steps) {
    lines.push(`# ${step.description}`);
    if (step.command) {
      lines.push(step.command);
    }
    lines.push("");
  }

  return lines.join("\n");
}

export function generateTfmigrateHcl(graph: DependencyGraph, cutEdges: CutEdge[]): string {
  // Group moves by from_dir/to_dir pair
  const groups = new Map<string, { fromDir: string; toDir: string; actions: string[] }>();

  for (const cut of cutEdges) {
    const fromNode = graph.nodes.get(cut.edge.from);
    if (!fromNode) continue;

    const fromDir = fromNode.repo;
    const toDir = cut.toNamespace;
    const key = `${fromDir}|${toDir}`;

    if (!groups.has(key)) {
      groups.set(key, { fromDir, toDir, actions: [] });
    }
    const action = `mv ${fromNode.resourceType}.${fromNode.name} ${fromNode.resourceType}.${fromNode.name}`;
    const group = groups.get(key)!;
    if (!group.actions.includes(action)) {
      group.actions.push(action);
    }
  }

  const blocks: string[] = [];
  for (const [, group] of groups) {
    const migrationName = `move_to_${group.toDir.replace(/-/g, "_")}`;
    const actionsStr = group.actions.map((a) => `    "${a}",`).join("\n");
    blocks.push(`migration "multi_state" "${migrationName}" {
  from_dir = "${group.fromDir}"
  to_dir   = "${group.toDir}"
  actions = [
${actionsStr}
  ]
}`);
  }

  return blocks.join("\n\n") + "\n";
}

export function createMigrationPlan(graph: DependencyGraph, config?: NamespaceConfig): MigrationPlan {
  const crossNamespaceEdges = findCrossNamespaceEdges(graph, config);
  const steps = generateMigrationSteps(graph, crossNamespaceEdges);
  const shellScript = generateShellScript(steps);
  const json = JSON.stringify({ steps, crossNamespaceEdges }, null, 2);
  const tfmigrateHcl = generateTfmigrateHcl(graph, crossNamespaceEdges);

  return { steps, crossNamespaceEdges, shellScript, json, tfmigrateHcl };
}
