import type { MigrateResult, FileWrite, ImportBlock, RemovedBlock } from "../types.js";
import { getOrCreate } from "../utils/map-utils.js";

export interface RollbackPlan {
  description: string;
  steps: string[];
  fileWrites: FileWrite[];
  tfmigrateHcl: string;
}

/**
 * Generate a rollback plan that reverses a migration.
 * The rollback uses the same mechanism (import/removed blocks) in reverse:
 * - Resources imported into target → generate removed blocks to release them from target
 * - Resources removed from source → generate import blocks to re-import them into source
 *
 * For import blocks in the rollback, resource IDs are resolved from the original
 * migration's import blocks (which already contain the correct IDs from state).
 */
export function generateRollbackPlan(result: MigrateResult): RollbackPlan {
  const steps: string[] = [];
  const fileWrites: FileWrite[] = [];

  // Build a map of resource address → ID from the original import blocks
  // These IDs were resolved from state during the forward migration
  const addressToId = new Map<string, string>();
  for (const imp of result.importBlocks) {
    addressToId.set(imp.to, imp.id);
  }

  // Reverse import blocks: what was imported into target should be removed from target
  const reverseRemovedBlocks: RemovedBlock[] = result.importBlocks.map((imp) => ({
    from: imp.to,
    repo: imp.repo,
    destroy: false,
  }));

  // Reverse removed blocks: what was removed from source should be imported back
  // Use the resolved ID from the forward migration's import blocks
  const reverseImportBlocks: ImportBlock[] = result.removedBlocks.map((rem) => ({
    to: rem.from,
    id: addressToId.get(rem.from) || "<RESOURCE_ID>",
    repo: rem.repo,
  }));

  // Generate rollback import.tf for source repos (re-import resources)
  const importsByRepo = new Map<string, ImportBlock[]>();
  for (const imp of reverseImportBlocks) {
    getOrCreate(importsByRepo, imp.repo, () => []).push(imp);
  }

  for (const [repo, imports] of importsByRepo) {
    const content = imports.map((imp) =>
      `import {\n  to = ${imp.to}\n  id = "${imp.id}"\n}\n`
    ).join("\n");
    steps.push(`Add import blocks to ${repo} to re-import resources`);
    fileWrites.push({
      filePath: `${repo}/rollback-imports.tf`,
      content: `# Rollback: re-import resources that were removed\n# Run: terraform apply in ${repo}\n# After successful apply, remove this file and restore the original resource blocks.\n\n${content}`,
      operation: "create",
    });
  }

  // Generate rollback removed.tf for target repos (release resources)
  const removedByRepo = new Map<string, RemovedBlock[]>();
  for (const rem of reverseRemovedBlocks) {
    getOrCreate(removedByRepo, rem.repo, () => []).push(rem);
  }

  for (const [repo, removals] of removedByRepo) {
    const content = removals.map((rem) =>
      `removed {\n  from = ${rem.from}\n\n  lifecycle {\n    destroy = false\n  }\n}\n`
    ).join("\n");
    steps.push(`Add removed blocks to ${repo} to drop resources without destroying`);
    fileWrites.push({
      filePath: `${repo}/rollback-removed.tf`,
      content: `# Rollback: release resources from this state (no destroy)\n# Run: terraform apply in ${repo}\n# After successful apply, remove this file and the migrated resource blocks.\n\n${content}`,
      operation: "create",
    });
  }

  // Generate rollback shell script guidance
  if (reverseImportBlocks.length > 0 || reverseRemovedBlocks.length > 0) {
    const sourceRepos = [...importsByRepo.keys()];
    const targetRepos = [...removedByRepo.keys()];

    const scriptLines = [
      "#!/bin/bash",
      "set -euo pipefail",
      "",
      "# Rollback Script — reverses the migration",
      "# Generated by terraform-state-mover",
      "#",
      "# Prerequisites:",
      "#   1. Copy rollback-removed.tf into the target repo(s)",
      "#   2. Copy rollback-imports.tf into the source repo(s)",
      "#   3. Restore the original resource blocks in the source repo(s)",
      "#   4. Remove the migrated resource blocks from the target repo(s)",
      "",
      "echo '=== Step 1: Release resources from target state ==='",
      "",
    ];

    for (const repo of targetRepos) {
      scriptLines.push(`echo "Applying removed blocks in ${repo}..."`);
      scriptLines.push(`terraform -chdir="${repo}" apply -auto-approve`);
      scriptLines.push("");
    }

    scriptLines.push("echo '=== Step 2: Re-import resources into source state ==='");
    scriptLines.push("");

    for (const repo of sourceRepos) {
      scriptLines.push(`echo "Applying import blocks in ${repo}..."`);
      scriptLines.push(`terraform -chdir="${repo}" apply -auto-approve`);
      scriptLines.push("");
    }

    scriptLines.push("echo '=== Step 3: Verify ==='");
    scriptLines.push("");
    for (const repo of [...targetRepos, ...sourceRepos]) {
      scriptLines.push(`terraform -chdir="${repo}" plan -detailed-exitcode || {`);
      scriptLines.push(`  echo "WARNING: ${repo} has unexpected changes after rollback."`);
      scriptLines.push(`}`);
      scriptLines.push("");
    }

    scriptLines.push("echo '=== Step 4: Cleanup ==='");
    scriptLines.push("");
    scriptLines.push("# Remove rollback files after successful verification:");
    for (const repo of sourceRepos) {
      scriptLines.push(`# rm ${repo}/rollback-imports.tf`);
    }
    for (const repo of targetRepos) {
      scriptLines.push(`# rm ${repo}/rollback-removed.tf`);
    }
    scriptLines.push("");
    scriptLines.push("echo 'Rollback complete.'");

    fileWrites.push({
      filePath: "rollback.sh",
      content: scriptLines.join("\n"),
      operation: "create",
    });
  }

  // Generate tfmigrate HCL for rollback (reverse direction)
  const tfmigrateLines = ["migration \"multi_state\" {"];
  for (const move of result.moves) {
    // Reverse: target → source
    tfmigrateLines.push(`  state_mv "${move.targetRepo}" "${move.sourceRepo}" "${move.block.resourceType}.${move.block.name}"`);
  }
  tfmigrateLines.push("}");
  const tfmigrateHcl = tfmigrateLines.length > 2 ? tfmigrateLines.join("\n") : "";

  steps.push("Run terraform apply in both repos to execute rollback");
  steps.push("Run terraform plan in both repos to verify: expect no changes");

  return {
    description: `Rollback plan: reverses ${result.summary.resourcesMoved} resource moves, ${result.importBlocks.length} imports`,
    steps,
    fileWrites,
    tfmigrateHcl,
  };
}
