# Removed blocks generated by terraform-state-mover (TF 1.7+)
# Run: terraform apply (removes resource from this state WITHOUT destroying)
# After successful apply, remove this file.

removed {
  from = aws_iam_role.app_analytics_s3_access

  lifecycle {
    destroy = false
  }
}

removed {
  from = aws_iam_role.app_api_db_access

  lifecycle {
    destroy = false
  }
}

removed {
  from = aws_iam_role.app_api_lambda_exec

  lifecycle {
    destroy = false
  }
}
